### ISSUE TITLE
adding index fails

### ISSUE THREAD

**Issue by marr** [hiromipaw/wikicat#4]
After following books instructions on how to build the links index:

```
$ bundle exec rake db:migrate
== 20151110014616 AddIndexToLinks: migrating ==================================
-- add_index(:links, :cl_sortkey)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: BLOB/TEXT column 'cl_sortkey' used in key specification without a key length: CREATE  INDEX `index_links_on_cl_sortkey`  ON `links` (`cl_sortkey`) /Users/dmarr/wikicat/db/migrate/20151110014616_add_index_to_links.rb:3:in `change'
ActiveRecord::StatementInvalid: Mysql2::Error: BLOB/TEXT column 'cl_sortkey' used in key specification without a key length: CREATE  INDEX `index_links_on_cl_sortkey`  ON `links` (`cl_sortkey`)
/Users/dmarr/wikicat/db/migrate/20151110014616_add_index_to_links.rb:3:in `change'
Mysql2::Error: BLOB/TEXT column 'cl_sortkey' used in key specification without a key length
/Users/dmarr/wikicat/db/migrate/20151110014616_add_index_to_links.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)`
``
```

**Comment by marr** [comment]
Migrating over to postgresql did get past that..

**Comment by hiromipaw** [comment]
Hi @marr,
Thanks for reaching out. Are you using the dump from dropbox or a new one?

**Comment by crose1000** [comment]
I have an identical issue. I think this link explains it.
http://stackoverflow.com/questions/1827063/mysql-error-key-specification-without-a-key-length
I am using this to learn rails, so I do not yet understand how to fix or workaround. I tried
    add_index :links, :cl_sortkey(255) 
in 20140908145510_add_index_to_links,  and this is not syntactically correct.
Any suggestions?

**Comment by crose1000** [comment]
```
add_index :links, :cl_sortkey, :length => { :cl_sortkey => 255 }
```

worked for me
